<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nguoidung extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Nguoidung_model');
    } 

    /*
     * Listing of nguoidung
     */
    function index()
    {
        $data['nguoidung'] = $this->Nguoidung_model->get_all_nguoidung();
        
        $data['_view'] = 'nguoidung/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new nguoidung
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TRANGTHAI' => $this->input->post('TRANGTHAI'),
				'MADANHGIA' => $this->input->post('MADANHGIA'),
				'MAQUYEN' => $this->input->post('MAQUYEN'),
				'USERNAME' => $this->input->post('USERNAME'),
				'PASSWORD' => $this->input->post('PASSWORD'),
				'PASSWORD_RESET' => $this->input->post('PASSWORD_RESET'),
				'HOTEN' => $this->input->post('HOTEN'),
				'NGAYSINH' => $this->input->post('NGAYSINH'),
				'EMAIL' => $this->input->post('EMAIL'),
				'NGAYTAO' => $this->input->post('NGAYTAO'),
				'NGAYSUA' => $this->input->post('NGAYSUA'),
				'VAITRO' => $this->input->post('VAITRO'),
            );
            
            $nguoidung_id = $this->Nguoidung_model->add_nguoidung($params);
            redirect('nguoidung/index');
        }
        else
        {            
            $data['_view'] = 'nguoidung/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a nguoidung
     */
    function edit($MANGUOIDUNG)
    {   
        // check if the nguoidung exists before trying to edit it
        $data['nguoidung'] = $this->Nguoidung_model->get_nguoidung($MANGUOIDUNG);
        
        if(isset($data['nguoidung']['MANGUOIDUNG']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TRANGTHAI' => $this->input->post('TRANGTHAI'),
					'MADANHGIA' => $this->input->post('MADANHGIA'),
					'MAQUYEN' => $this->input->post('MAQUYEN'),
					'USERNAME' => $this->input->post('USERNAME'),
					'PASSWORD' => $this->input->post('PASSWORD'),
					'PASSWORD_RESET' => $this->input->post('PASSWORD_RESET'),
					'HOTEN' => $this->input->post('HOTEN'),
					'NGAYSINH' => $this->input->post('NGAYSINH'),
					'EMAIL' => $this->input->post('EMAIL'),
					'NGAYTAO' => $this->input->post('NGAYTAO'),
					'NGAYSUA' => $this->input->post('NGAYSUA'),
					'VAITRO' => $this->input->post('VAITRO'),
                );

                $this->Nguoidung_model->update_nguoidung($MANGUOIDUNG,$params);            
                redirect('nguoidung/index');
            }
            else
            {
                $data['_view'] = 'nguoidung/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The nguoidung you are trying to edit does not exist.');
    } 

    /*
     * Deleting nguoidung
     */
    function remove($MANGUOIDUNG)
    {
        $nguoidung = $this->Nguoidung_model->get_nguoidung($MANGUOIDUNG);

        // check if the nguoidung exists before trying to delete it
        if(isset($nguoidung['MANGUOIDUNG']))
        {
            $this->Nguoidung_model->delete_nguoidung($MANGUOIDUNG);
            redirect('nguoidung/index');
        }
        else
            show_error('The nguoidung you are trying to delete does not exist.');
    }
    
}
