<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nguoidung_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get nguoidung by MANGUOIDUNG
     */
    function get_nguoidung($MANGUOIDUNG)
    {
        return $this->db->get_where('nguoidung',array('MANGUOIDUNG'=>$MANGUOIDUNG))->row_array();
    }
        
    /*
     * Get all nguoidung
     */
    function get_all_nguoidung()
    {
        $this->db->order_by('MANGUOIDUNG', 'desc');
        return $this->db->get('nguoidung')->result_array();
    }
        
    /*
     * function to add new nguoidung
     */
    function add_nguoidung($params)
    {
        $this->db->insert('nguoidung',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update nguoidung
     */
    function update_nguoidung($MANGUOIDUNG,$params)
    {
        $this->db->where('MANGUOIDUNG',$MANGUOIDUNG);
        return $this->db->update('nguoidung',$params);
    }
    
    /*
     * function to delete nguoidung
     */
    function delete_nguoidung($MANGUOIDUNG)
    {
        return $this->db->delete('nguoidung',array('MANGUOIDUNG'=>$MANGUOIDUNG));
    }
}
